### ISSUE TITLE
refactor with kotlinpoet

### ISSUE THREAD

**Issue by okou19900722** [vert-x3/vertx-lang-kotlin#115]
Hi, I refactored the dataObject with `kotlinpoet`
https://github.com/okou19900722/vertx-lang-kotlin/tree/kotlinpoet

If it is the right way, I will complete the extension function

**Comment by vietj** [comment]
we need to agree first whether or not that will be done during the vertx F2F meeting (with Guido), we'll keep the community updated

**Comment by gmariotti** [comment]
Hi @okou19900722, I had a discussion about KotlinPoet with @vietj and the rest of the Vert.x team during the F2F. The general agreement is that, at least for now, we should avoid using it. In this way, we avoid adding an extra dependency to the `gen` module and we won't depend on whether or not KotlinPoet will be maintained in the future.

For now, I think we should focus on documenting and improving the readability of what is already there, to make easier for others to contribute and reuse already working pieces.

**Comment by okou19900722** [comment]
All right, I just want to give you a little help. you seem to be not very familiar with the way vertx-codegen works.

**Comment by gmariotti** [comment]
Sorry @okou19900722, I didn't explain myself properly. You're doing an amazing job, in particular with the code generation, and I hope you can keep contributing to the project. My main concern now is that the Kotlin code generation is not documented anywhere, and, at least as a start, it would be nice to have a reference to it the README, so that others immediately know what the library is able to generate. What do you think? Can you look into it?

**Comment by okou19900722** [comment]
It's great.
Cause of my bad english,I can't give you some help, But I will contributing more to the project.
